<?php

namespace AppBundle\Repository;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends \Doctrine\ORM\EntityRepository
{
    public function countByDev()
    {
        $qb = $this->createQueryBuilder('e');
        $qb ->select($qb->expr()->count('e'));
        return (int) $qb->getQuery()->getSingleScalarResult();
    }

    public function hightId(){
        $qb = $this->createQueryBuilder('e');
        $qb ->select($qb->expr()->max('e'));
        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}
