<?php

namespace AppBundle\Repository;

/**
 * societyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class societyRepository extends \Doctrine\ORM\EntityRepository
{
}
