<?php

namespace AppBundle\Repository;

/**
 * SpreadSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpreadSheetRepository extends \Doctrine\ORM\EntityRepository
{
}
