<?php

namespace AppBundle\Repository;

/**
 * YearsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YearsRepository extends \Doctrine\ORM\EntityRepository
{
}
