app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
app_society:
    resource: "@AppBundle/Resources/config/routing/society.yml"
    prefix:   /society

app_sheet:
    resource: "@AppBundle/Resources/config/routing/sheet.yml"
    prefix:   /sheet

app_link:
    resource: "@AppBundle/Resources/config/routing/link.yml"
    prefix:   /link

app_sheetdev:
  resource: "@AppBundle/Resources/config/routing/sheetdev.yml"
  prefix:   /sheetdev

app_years:
  resource: "@AppBundle/Resources/config/routing/years.yml"
  prefix:   /years

app_provider:
  resource: "@AppBundle/Resources/config/routing/provider.yml"
  prefix:   /provider

app_delivery:
  resource: "@AppBundle/Resources/config/routing/delivery.yml"
  prefix:   /delivery
  
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"