app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
app_society:
    resource: "@AppBundle/Resources/config/routing/society.yml"
    prefix:   /society

app_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

app_sheet:
    resource: "@AppBundle/Resources/config/routing/sheet.yml"
    prefix:   /sheet

app_link:
    resource: "@AppBundle/Resources/config/routing/link.yml"
    prefix:   /link

app_sheetdev:
  resource: "@AppBundle/Resources/config/routing/sheetdev.yml"
  prefix:   /sheetdev
