# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                default_target_path: homepage
            
            logout:
                path: fos_user_security_logout
                target: password
            
            anonymous: true
    
    #   FOSUSER SECURITY
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    
    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/society, role: ROLE_USER }
        - { path: ^/sheet, role: ROLE_USER }
        - { path: ^/link, role: ROLE_USER }
        - { path: ^/sheetdev, role: ROLE_USER }
        - { path: ^/years, role: ROLE_USER }
        - { path: ^/provider, role: ROLE_USER }
        - { path: ^/delivery, role: ROLE_USER }
#        - { path: ^/, role: ROLE_ADMIN }
#        - { path: ^/society, role: ROLE_ADMIN }
#        - { path: ^/sheet, role: ROLE_ADMIN }
#        - { path: ^/link, role: ROLE_ADMIN }
#        - { path: ^/sheetdev, role: ROLE_ADMIN }
#        - { path: ^/years, role: ROLE_ADMIN }
#        - { path: ^/provider, role: ROLE_ADMIN }
#        - { path: ^/delivery, role: ROLE_ADMIN }
       