sheet_index:
    path:     /
    defaults: { _controller: "AppBundle:Sheet:index" }
    methods:  GET

#sheet_show:
#    path:     /{id}/show
#    defaults: { _controller: "AppBundle:Sheet:show" }
#    methods:  GET

sheet_spread:
    path:     /{id}/spread
    defaults: { _controller: "AppBundle:Sheet:spreadSheet" }
    methods:  [GET, POST]

sheet_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sheet:new" }
    methods:  [GET, POST]

sheet_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sheet:edit" }
    methods:  [GET, POST]

sheet_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sheet:delete" }
    methods:  DELETE
