AppBundle\Entity\Link:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        linkname:
            type: string
            length: 70
            nullable: true
        link:
            type: string
            length: 255
    oneToOne:
        sheetdev1:
            targetEntity: AppBundle\Entity\SheetDev
            inversedBy: link1
            joinColumn:
                name: sheetdev_id
                referencedColumnName: id
                onDelete: CASCADE
        sheet1:
            targetEntity: AppBundle\Entity\Sheet
            inversedBy: link2
            joinColumn:
                name: sheet_id
                referencedColumnName: id
                onDelete: CASCADE
        delivery1:
            targetEntity: AppBundle\Entity\Delivery
            inversedBy: link3
            joinColumn:
                name: delivery_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks: {  }
