AppBundle\Entity\Link:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\LinkRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        linkname:
            type: string
            length: '70'
            nullable: true
        link:
            type: string
            length: 255
            
    manyToOne:
        society:
            targetEntity: AppBundle\Entity\society
            inversedBy: link
            joinColumn:
                name: society_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
