AppBundle\Entity\SheetDev:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SheetDevRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        devis:
            type: boolean
            nullable: true
        date:
            type: datetime
        years:
            type: string
            length: 2
    manyToOne:
        society:
            targetEntity: AppBundle\Entity\society
            inversedBy: sheetdev
            joinColumn:
                name: society_id
                referencedColumnName: id
    oneToMany:
        sheet:
            targetEntity: AppBundle\Entity\Sheet
            mappedBy: years
    oneToOne:
        link1:
            targetEntity: AppBundle\Entity\Link
            mappedBy: sheetdev1

    lifecycleCallbacks: {  }
