AppBundle\Entity\Sheet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SheetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        facture:
            type: boolean
            nullable: true
        date:
            type: date
    manyToOne:
        provider:
            targetEntity: AppBundle\Entity\Provider
            inversedBy: sheet
            joinColumn:
                name: provider_id
                referencedColumnName: id
        years:
            targetEntity: AppBundle\Entity\Years
            inversedBy: sheet
            joinColumn:
                name: years_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
