AppBundle\Entity\Years:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\YearsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        years:
            type: string
            nullable: false
            length: 2
            unique: true
            
    oneToMany:
        sheetdev:
            targetEntity: AppBundle\Entity\SheetDev
            mappedBy: years
        sheet:
            targetEntity: AppBundle\Entity\Sheet
            mappedBy: years
    lifecycleCallbacks: {  }
