AppBundle\Entity\Years:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\YearsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        years:
            type: integer
            unique: true
    lifecycleCallbacks: {  }
